1-2 update_post
f-lab-edu/fastapi-restapi pull request #2
Opened 2024-06-28 12:08 UTC by sfdg4869

..

2024-06-29 05:46 UTC, f-lab-ydrah requested changes
코멘트 확인 해주세요 ㅎㅎ

2024-06-29 05:46 UTC, f-lab-ydrah commented on app/main.py
> +        raise HTTPException(status_code=404, detail="게시글이 없습니다..")
status code를 아주 잘 작성해주셨네요!

직접적으로 `404` 를 사용하는 것 보다 `fastapi.status` 모듈에 있는 상수를 쓰면 좀 더 시멘틱해지는데, 아래 내용 참고해서 수정해보시겠어요?

https://fastapi.tiangolo.com/reference/status/

2024-06-29 05:46 UTC, f-lab-ydrah commented on app/main.py
> +        raise HTTPException(status_code=404, detail="게시글이 없습니다..")
다른 곳도 마찬가지로요!

2024-06-29 05:46 UTC, f-lab-ydrah commented on app/main.py
> +        raise HTTPException(status_code=403, detail="작성자가 다릅니다..")
오 굿! 401과 403의 차이를 혹시 아실까요?

2024-06-29 05:46 UTC, f-lab-ydrah commented on app/main.py
> +    )
이렇게 전체를 수정하는건 PATCH가 아닌 PUT 방식입니다. 두 방식의 차이를 아실까요?
PATCH 방식으로 수정해주세요.

2024-06-29 05:46 UTC, f-lab-ydrah commented on app/main.py
> +@app.patch("/posts/{post_id}")
`respons_model` 도 추가해주세요.

2024-06-29 05:46 UTC, f-lab-ydrah commented on app/main.py
> +    return in_memory
데이터 전체를 내보내면, 데이터가 많을 때 문제가 되지 않을까요?
필요치 않다면 아무것도 반환하지 않는게 좋을거 같습니다. 이럴 땐 적당한 Status Code는 무엇일까요?

2024-06-29 06:16 UTC, sfdg4869 commented on app/main.py
> +        raise HTTPException(status_code=404, detail="게시글이 없습니다..")
넵! 수정하겠습니다!

2024-06-29 06:16 UTC, sfdg4869 commented on app/main.py
> +        raise HTTPException(status_code=403, detail="작성자가 다릅니다..")
401은 인증 , 403은 권한에 대한 문제로 알고있습니다!

2024-06-29 06:18 UTC, sfdg4869 commented on app/main.py
> +    )
아! PUT 방식이 전체를 수정하는 방식이고, PATCH 방식이 일부만 수정하는 방식입니다!
PATCH 방식에 맞게 다시 수정하겠습니다!

2024-06-29 06:21 UTC, sfdg4869 commented on app/main.py
> +    return in_memory
204 status code가 맞을거 같습니다! 데이터 전체를 내보내지 않도록 코드 수정하겠습니다!

2024-06-30 23:47 UTC, f-lab-ydrah approved these changes
👍 나머지 리뷰는 화요일 멘토링 시간에 같이 보시죠!

2024-07-02 13:19 UTC, merged